import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NavBar , Footer } from "@/components/Widgets";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const outfit = Outfit({subsets : ["latin"]})
// const rubik = Rubik({subsets : ["latin"]})
// const oswald = Oswald({subsets : ["latin"]})

export const metadata: Metadata = {
  title: "Trilox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className}`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
